###############################################################################
#
# Created by Jim Kornelsen on March 25, 2019
#
# I used the following powershell command to run on Windows.
# On Linux, LibreOffice libraries are typically more built-in, so simply
# calling "python3" is enough.
#
# & "C:/Program Files (x86)/LibreOffice/program/python.exe" cov.py
#
###############################################################################
import collections
import datetime
import io
import sys

import uno

sys.path.append('../../LinguisticTools/pythonpath')
from lingt.app.data.lingex_structs import (
    LingGramExample, LingGramMorph, LingGramWord)

InputLines = collections.namedtuple('InputLines', ['text', 'gloss', 'ft'])
phrases = [(
    'Dit is een Nederlands voorbeeld',
    'This is a Dutch example',
    'This is an example in Dutch.')]

examples = list()
for s in phrases:
    text_line, gloss_line, ft_line = s
    ex = LingGramExample()
    ex.freeTrans = ft_line
    for wordnum in range(len(text_line.split())):
        # XXX: This parsing is probably overly simplistic.
        text = text_line.split()[wordnum]
        gloss = gloss_line.split()[wordnum]
        morph = LingGramMorph()
        morph.text1 = text
        morph.gloss = gloss
        ex.appendMorphObj(morph)
        ex.appendWord(text, '')
    examples.append(ex)
    
    outfile = io.open("cov.xml", mode='w', encoding='UTF8')
    now = datetime.datetime.now()
    header = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!--\n'
        'This file was generated by a script for the '
        'LibreOffice Linguistic Tools.\n'
        '\n'
        'Date Generated: %s.\n'
        '-->\n'
        '<database>\n') % now.strftime("%d-%b-%Y")
    outfile.write(header)
    ref_number = 1
    for ex in examples:
        outfile.write('<refGroup><ref>%04d</ref>\n' % ref_number)
        for word in ex.wordList:
            outfile.write('<txGroup><tx>%s</tx>\n' % word.text1)
            for morph in word.morphList:
                outfile.write('<mbGroup>\n')
                outfile.write('<mb>%s</mb>\n' % morph.text1)
                outfile.write('<ge>%s</ge>\n' % morph.gloss)
                outfile.write('<ps>%s</ps>\n' % morph.pos)
                outfile.write('</mbGroup>\n')
            outfile.write('</txGroup>\n')
        outfile.write('<ft>%s</ft>\n' % ex.freeTrans)
        outfile.write('</refGroup>\n')
        ref_number += 1
    outfile.write('</database>\n')
    outfile.close()

