#include <com/sun/star/uno/XInterface.idl>

module com { module doobiecompany { module examples { module DoobieDoo {

    interface XDoobieDoo
    {
      long doobieMult( [in] long a, [in] long b );
      string doobieConcat( [in] string s1, [in] string s2 );
      string doobieConcatTwo( [in] string s1, [in] string s2 );
      string doobieRev( [in] string s1 );
    };

}; }; }; };
