/*************************************************************************
 *
 * History:
#   Adapted from the SDK examples by Jim Kornelsen on 02/23/10
 *
 *************************************************************************/

#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/lang/IllegalArgumentException.idl>

module lingtools_module
{
    interface XCallableSEC
    {
        boolean PickConverter();
        boolean SetConverter([in] string val, [in] boolean directionFw,
                             [in] long normalize);
        string  Convert([in] string val);
        string  GetName();
        long    GetNormalize();
        boolean GetDirectionFw();
    };
    service SEC_Call : XCallableSEC;
};

