"""
Information about Unicode characters, scripts and fonts.
Part of this file is generated by scripts in build/generating_code,
as described below.
"""
import string
from lingt.utils import unicode_data

# Useful to look up the type of a letter.
# Types are "WI_Vowels", "DepVowels", "AnyVowels", "WI_Consonants",
# "WF_Consonants", "AnyConsonants",
LetterIndex = {}
for script, lettertypes in unicode_data.SCRIPT_LETTERS.items():
    for lettertype, codes in lettertypes.items():
        for code in codes:
            LetterIndex[code] = lettertype
for lettertype, codes in unicode_data.OTHER_KNOWN_LETTERS.items():
    for code in codes:
        LetterIndex[code] = lettertype

# These values are used to strip punctuation and numbers from words.
PUNCTUATION = (
    [chr(i) for i in range(33, 47+1)] +
    [chr(i) for i in range(48, 57+1)] +               # digits
    [chr(i) for i in range(58, 64+1)] +
    [chr(i) for i in range(91, 96+1)] +
    [chr(i) for i in range(0x2018, 0x201F)]) # smart quotes

VIRAMA = {
    "BENGALI": "\u09CD",    # Halant
    "DEVANAGARI": "\u094D",
    "GUJARATI": "\u0ACD",
    "GURMUKHI": "\u0A4D",
    "HEBREW": "\u05B0",    # Sheva
    "KANNADA": "\u0CCD",
    "MALAYALAM": "\u0D4D",
    "ORIYA": "\u0B4D",
    "TAMIL": "\u0BCD",
    "TELUGU": "\u0C4D",
    }


# The font lists below are compiled from several online lists.
# See for example:
#   https://en.wikipedia.org/wiki/
#       List_of_typefaces_included_with_Microsoft_Windows
#

LATIN_FONTS = [
    "Arial", "Arial Nova", "Calibri", "Calisto MT", "Cambria", "Candara",
    "Century Gothic", "Chicago", "Comic Sans MS", "Consolas", "Constantia",
    "Corbel", "Courier New", "Georgia", "Georgia Pro", "Gill Sans Nova",
    "Helvetica", "Impact", "Lucida Sans Unicode", "Microsoft Sans Serif",
    "Palatino", "Palatino Linotype", "Rockwell Nova", "Sitka Text",
    "Tahoma", "Times New Roman", "Trebuchet MS", "Verdana", "Westminster"]

SCRIPT_FONTS = {
    "ARABIC": [
        "AlBayan", "Aldhabi", "Andalus", "Arabic Transparent",
        "Arabic Typesettings",
        "Arial", "Baghdad", "Courier New", "DecoTypeNaskh",
        "Droid Arabic Naskh",
        "Estrangelo Edessa", "Geeza", "Geeza Pro",
        "KacstOne", "Kalimati", "Kalyani",
        "KufiStandard GK", "Microsoft Sans Serif", "Microsoft Uighur",
        "Nadeem", "Sakkal Majalla", "Scheherazade", "Simplified Arabic",
        "TAMu_Kadambri", "TAMu_Kalyani", "TAMu_Maduram", "TLArabic",
        "Tahoma", "Times New Roman", "Traditional Arabic",
        "Urdu Typesetting"],
    "ARMENIAN": [
        "Droid Sans Armenian", "JF Armenian Serif", "Mshtakan", "Sylfaen",
        "Times New Roman"],
    "BALINESE": [],
    "BAMUM": [],
    "BATAK": [],
    "BENGALI": [
        "Ani", "Jamrul", "Likhan", "Lohit Bengali",
        "Mitra Mono", "Mukti Narrow", "Shonar Bangla", "Vrinda"],
    "BOPOMOFO": [],
    "BUGINESE": [],
    "BUHID": [],
    "CHAM": [],
    "CHEROKEE": ["Gadugi", "Plantagenet Cherokee"],
    "COPTIC": ["Sinaiticus"],
    "CYRILLIC": LATIN_FONTS,
    "DEVANAGARI": [
        "Annapurna", "Aparajita", "CDAC-GIST Surekh", "Chandas",
        "Devanagari", "DevanagariMT", "Jana Hindi", "Kalimati", "Kokila",
        "Lohit Hindi", "Mangal", "Raavi", "Raghu8", "Samanata",
        "Sanskrit Text", "Saraswati5", "Utsaah", "Xdvng", "Yogesh",
        "gargi"],
    "GEORGIAN": ["JF Georgian Contrast", "Sylfaen"],
    "GLAGOLITIC": [],
    "GREEK": LATIN_FONTS,
    "GUJARATI": [
        "Gujarati", "GujaratiMT", "Lohit Gujarati", "Rekha", "Saab",
        "Shruti", "aakar", "padmaa"],
    "GURMUKHI": ["Gurmukhi", "Lohit Punjabi", "Raavi"],
    "HANGUL": [
        "#Gungseouche", "#Pilgiche", "Apple Gothic", "AppleGothic",
        "Baekmuk Batang", "Baekmuk Dotum", "Baekmuk Gulim", "Batang",
        "BatangChe", "Dotum", "DotumChe", "Gulim", "GulimChe", "Gungsuh",
        "GungsuhChe", "GungSeo", "Hangangche", "Jung Gothic",
        "Malgun Gothic", "PCMyungjo", "PilGi", "Seoul", "Tae Graphic"],
    "HANUNOO": [],
    "HEBREW": [
        "Aharoni", "Aharoni Bold", "Arial", "Arial Hebrew", "ArialHB",
        "Corsiva", "Corsiva Hebrew", "Courier New", "David",
        "Droid Sans Hebrew", "Ezra SIL",
        "FrankRuehl", "Gisha", "Hebrew", "Levenim MT",
        "Lucida Sans Unicode", "Microsoft Sans Serif", "Miriam",
        "Miriam Fixed",
        "Narkisim", "New Peninim", "NewPeninimMT", "Raanana", "Rod",
        "Tahoma", "Times New Roman"],
    "HIRAGANA": [
        "AquaKanaRegular", "Droid Sans Japanese",
        "Hiragino Kaku Gothic Pro", "Kochi Mincho",
        "MS Gothic", "MS PGothic", "MS UI Gothic",
        "MS Mincho", "MS PMincho", "Meiryo", "Meiryo UI",
        "Osaka", "Yu Gothic", "Yu Mincho"],
    "JAVANESE": [],
    "KANNADA": ["Kedage", "Mallig", "Tunga"],
    "KATAKANA": [
        "AquaKanaRegular", "Droid Sans Japanese",
        "Hiragino Kaku Gothic Pro", "Kochi Mincho",
        "MS Gothic", "MS Mincho", "Meiryo", "Osaka", "Yu Gothic",
        "Yu Mincho"],
    "KHMER": ["DaunPenh", "Khmer OS", "Khmer UI", "MoolBoran"],
    "LAO": ["DokChampa", "Lao UI", "Phetsarath OT"],
    "LATIN": LATIN_FONTS,
    "LEPCHA": [],
    "LIMBU": [],
    "LISU": [],
    "MALAYALAM": [
        "Kartika", "Karthika", "Lohit Malayalam", "Meera", "Rachana"],
    "MANDAIC": [],
    "MONGOLIAN": ["Mongolian Baiti"],
    "MYANMAR": ["Myanmar Text", "Padauk"],
    "NKO": ["Ebrima"],
    "OGHAM": [],
    "ORIYA": [
        "Kalinga", "Khondi", "Lohit Oriya", "Oriya", "Santali", "oriUni",
        "utkal"],
    "REJANG": [],
    "RUNIC": [],
    "SAMARITAN": [],
    "SAURASHTRA": [],
    "SINHALA": ["Iskoola Pota", "LKLUG"],
    "SUNDANESE": [],
    "SYRIAC": ["Estrangelo Edessa"],
    "TAGALOG": [],
    "TAGBANWA": [],
    "TAMIL": [
        "Inai Mathi", "InaiMathi", "JanaTamil", "Latha", "Lohit Tamil",
        "Tau Elango Barathi", "ThendraUni", "TheneeUni", "VaigaiUni",
        "Vijaya", "aAvarangal"],
    "TELUGU": [
        "Gautami", "Lohit Telugu", "Pothana2000", "Vani", "Vemana2000"],
    "THAANA": ["MV Boli"],
    "THAI": [
        "Angsana New", "AngsanaUPC", "Ayuthaya", "Browallia",
        "Browallia New", "BrowalliaUPC", "Cordia New", "CordiaUPC",
        "Dillenia", "DilleniaUPC", "Droid Sans Thai",
        "Eucrosia", "EucrosiaUPC", "Freesia", "FreesiaUPC", "Garuda",
        "IrisUPC", "JasmineUPC", "Jumpa", "Kinnari",
        "KodchiangUPC", "Krungthep",
        "Leelawadee", "Leelawadee UI", "LilyUPC", "Loma",
        "Microsoft Sans Serif", "Norasi", "Purisa", "Sathu",
        "Sawasdee", "Silom",
        "Tahoma", "Thonburi", "Tlwg Typist", "Umpush", "Waree"],
    "TIBETAN": ["Microsoft Himalaya"],
    "TIFINAGH": ["Ebrima"],
}

# For fonts that support a number of different scripts
FONT_SCRIPTS = {
    "Akshar Unicode" : [
        "DEVANAGARI", "KANNADA", "MALAYALAM", "TAMIL", "TELUGU"],
    "Arial Unicode MS" : [
        "ARABIC", "ARMENIAN", "CYRILLIC", "DEVANAGARI", "GEORGIAN",
        "GREEK", "GURMUKHI", "HEBREW", "HIRAGANA", "KANNADA", "HANGUL",
        "TAMIL", "THAI"],
    "DejaVu Serif" : [
        "ARABIC", "ARMENIAN", "CYRILLIC", "GREEK", "HEBREW", "LAO"],
    "Gentium" : ["CYRILLIC", "GREEK"],
    "FreeSerif" : [
        "BENGALI", "CYRILLIC", "GREEK", "DEVANAGARI", "GURMUKHI",
        "HEBREW", "HIRAGANA", "KATAKANA", "MALAYALAM", "TAMIL", "TELUGU",
        "THAANA", "THAI"],
    "Nirmala UI" : [
        "DEVANAGARI", "BENGALI", "GURMUKHI", "GUJARATI", "ORIYA",
        "TAMIL", "TELEGU", "KANNADA", "MALAYALAM", "SINHALA"],
    "Segoe UI" : [
        "ARABIC", "ARMENIAN", "CYRILLIC", "GEORGIAN", "GREEK",
        "HEBREW", "LATIN", "LISU"],
    }

# CASE_CAPITALS and CASE_LOWER are generated by grab_case_pairs.py.
#
# They are in the same order, so for example the lowercase equivalent of
# CASE_CAPITALS[0] is CASE_LOWER[0].

CASE_CAPITALS = [
        "\u0041","\u0042","\u0043","\u0044","\u0045","\u0046","\u0047",
        "\u0048","\u0049","\u004A","\u004B","\u004C","\u004D","\u004E",
        "\u004F","\u0050","\u0051","\u0052","\u0053","\u0054","\u0055",
        "\u0056","\u0057","\u0058","\u0059","\u005A","\u00C6","\u00D0",
        "\u00DE","\u014A","\u018F","\u0194","\u0196","\u01A2","\u01A9",
        "\u01B1","\u01B7","\u01F6","\u01F7","\u021C","\u0222","\u0370",
        "\u037F","\u0391","\u0392","\u0393","\u0394","\u0395","\u0396",
        "\u0397","\u0398","\u0399","\u039A","\u039B","\u039C","\u039D",
        "\u039E","\u039F","\u03A0","\u03A1","\u03A3","\u03A4","\u03A5",
        "\u03A6","\u03A7","\u03A8","\u03A9","\u03E2","\u03E4","\u03E6",
        "\u03E8","\u03EA","\u03EC","\u03EE","\u03F7","\u03FA","\u0401",
        "\u0402","\u0403","\u0405","\u0407","\u0408","\u0409","\u040A",
        "\u040B","\u040C","\u040F","\u0410","\u0411","\u0412","\u0413",
        "\u0414","\u0415","\u0416","\u0417","\u0418","\u041A","\u041B",
        "\u041C","\u041D","\u041E","\u041F","\u0420","\u0421","\u0422",
        "\u0423","\u0424","\u0425","\u0426","\u0427","\u0428","\u0429",
        "\u042B","\u042D","\u042E","\u042F","\u0460","\u0462","\u046E",
        "\u0470","\u0472","\u0474","\u0478","\u047E","\u0480","\u04BA",
        "\u04D8","\u0514","\u0516","\u0518","\u051A","\u051C","\u052A",
        "\u052C","\u0531","\u0532","\u0533","\u0534","\u0535","\u0536",
        "\u0537","\u0538","\u0539","\u053A","\u053B","\u053C","\u053D",
        "\u053E","\u053F","\u0540","\u0541","\u0542","\u0543","\u0544",
        "\u0545","\u0546","\u0547","\u0548","\u0549","\u054A","\u054B",
        "\u054C","\u054D","\u054E","\u054F","\u0550","\u0551","\u0552",
        "\u0553","\u0554","\u0555","\u0556","\u10A0","\u10A1","\u10A2",
        "\u10A3","\u10A4","\u10A5","\u10A6","\u10A7","\u10A8","\u10A9",
        "\u10AA","\u10AB","\u10AC","\u10AD","\u10AE","\u10AF","\u10B0",
        "\u10B1","\u10B2","\u10B3","\u10B4","\u10B5","\u10B6","\u10B7",
        "\u10B8","\u10B9","\u10BA","\u10BB","\u10BC","\u10BD","\u10BE",
        "\u10BF","\u10C0","\u10C1","\u10C2","\u10C3","\u10C4","\u10C5",
        "\u10C7","\u10CD","\u2C00","\u2C01","\u2C02","\u2C03","\u2C04",
        "\u2C05","\u2C06","\u2C07","\u2C08","\u2C09","\u2C0B","\u2C0C",
        "\u2C0D","\u2C0E","\u2C0F","\u2C10","\u2C11","\u2C12","\u2C13",
        "\u2C14","\u2C15","\u2C16","\u2C17","\u2C18","\u2C19","\u2C1A",
        "\u2C1B","\u2C1C","\u2C1D","\u2C1E","\u2C1F","\u2C20","\u2C21",
        "\u2C23","\u2C26","\u2C2A","\u2C2B","\u2C2C","\u2C6D","\u2C80",
        "\u2C82","\u2C84","\u2C86","\u2C88","\u2C8A","\u2C8C","\u2C8E",
        "\u2C90","\u2C92","\u2C94","\u2C96","\u2C98","\u2C9A","\u2C9C",
        "\u2C9E","\u2CA0","\u2CA2","\u2CA4","\u2CA6","\u2CA8","\u2CAA",
        "\u2CAC","\u2CAE","\u2CB0","\u2CC0","\uA640","\uA642","\uA646",
        "\uA648","\uA65E","\uA680","\uA682","\uA684","\uA686","\uA688",
        "\uA68C","\uA68E","\uA690","\uA692","\uA694","\uA696","\uA726",
        "\uA728","\uA72A","\uA72C","\uA732","\uA734","\uA736","\uA738",
        "\uA73C","\uA74E","\uA760","\uA768","\uA76A","\uA76C","\uA76E",
        "\uA78B","\uA7B3","\uA7B4","\uA7B6"]

# lower case equivalent of CaseCapital at same index
CASE_LOWER = [
        "\u0061","\u0062","\u0063","\u0064","\u0065","\u0066","\u0067",
        "\u0068","\u0069","\u006A","\u006B","\u006C","\u006D","\u006E",
        "\u006F","\u0070","\u0071","\u0072","\u0073","\u0074","\u0075",
        "\u0076","\u0077","\u0078","\u0079","\u007A","\u00E6","\u00F0",
        "\u00FE","\u014B","\u0259","\u0263","\u0269","\u01A3","\u0283",
        "\u028A","\u0292","\u0195","\u01BF","\u021D","\u0223","\u0371",
        "\u03F3","\u03B1","\u03B2","\u03B3","\u03B4","\u03B5","\u03B6",
        "\u03B7","\u03B8","\u03B9","\u03BA","\u03BB","\u03BC","\u03BD",
        "\u03BE","\u03BF","\u03C0","\u03C1","\u03C3","\u03C4","\u03C5",
        "\u03C6","\u03C7","\u03C8","\u03C9","\u03E3","\u03E5","\u03E7",
        "\u03E9","\u03EB","\u03ED","\u03EF","\u03F8","\u03FB","\u0451",
        "\u0452","\u0453","\u0455","\u0457","\u0458","\u0459","\u045A",
        "\u045B","\u045C","\u045F","\u0430","\u0431","\u0432","\u0433",
        "\u0434","\u0435","\u0436","\u0437","\u0438","\u043A","\u043B",
        "\u043C","\u043D","\u043E","\u043F","\u0440","\u0441","\u0442",
        "\u0443","\u0444","\u0445","\u0446","\u0447","\u0448","\u0449",
        "\u044B","\u044D","\u044E","\u044F","\u0461","\u0463","\u046F",
        "\u0471","\u0473","\u0475","\u0479","\u047F","\u0481","\u04BB",
        "\u04D9","\u0515","\u0517","\u0519","\u051B","\u051D","\u052B",
        "\u052D","\u0561","\u0562","\u0563","\u0564","\u0565","\u0566",
        "\u0567","\u0568","\u0569","\u056A","\u056B","\u056C","\u056D",
        "\u056E","\u056F","\u0570","\u0571","\u0572","\u0573","\u0574",
        "\u0575","\u0576","\u0577","\u0578","\u0579","\u057A","\u057B",
        "\u057C","\u057D","\u057E","\u057F","\u0580","\u0581","\u0582",
        "\u0583","\u0584","\u0585","\u0586","\u2D00","\u2D01","\u2D02",
        "\u2D03","\u2D04","\u2D05","\u2D06","\u2D07","\u2D08","\u2D09",
        "\u2D0A","\u2D0B","\u2D0C","\u2D0D","\u2D0E","\u2D0F","\u2D10",
        "\u2D11","\u2D12","\u2D13","\u2D14","\u2D15","\u2D16","\u2D17",
        "\u2D18","\u2D19","\u2D1A","\u2D1B","\u2D1C","\u2D1D","\u2D1E",
        "\u2D1F","\u2D20","\u2D21","\u2D22","\u2D23","\u2D24","\u2D25",
        "\u2D27","\u2D2D","\u2C30","\u2C31","\u2C32","\u2C33","\u2C34",
        "\u2C35","\u2C36","\u2C37","\u2C38","\u2C39","\u2C3B","\u2C3C",
        "\u2C3D","\u2C3E","\u2C3F","\u2C40","\u2C41","\u2C42","\u2C43",
        "\u2C44","\u2C45","\u2C46","\u2C47","\u2C48","\u2C49","\u2C4A",
        "\u2C4B","\u2C4C","\u2C4D","\u2C4E","\u2C4F","\u2C50","\u2C51",
        "\u2C53","\u2C56","\u2C5A","\u2C5B","\u2C5C","\u0251","\u2C81",
        "\u2C83","\u2C85","\u2C87","\u2C89","\u2C8B","\u2C8D","\u2C8F",
        "\u2C91","\u2C93","\u2C95","\u2C97","\u2C99","\u2C9B","\u2C9D",
        "\u2C9F","\u2CA1","\u2CA3","\u2CA5","\u2CA7","\u2CA9","\u2CAB",
        "\u2CAD","\u2CAF","\u2CB1","\u2CC1","\uA641","\uA643","\uA647",
        "\uA649","\uA65F","\uA681","\uA683","\uA685","\uA687","\uA689",
        "\uA68D","\uA68F","\uA691","\uA693","\uA695","\uA697","\uA727",
        "\uA729","\uA72B","\uA72D","\uA733","\uA735","\uA737","\uA739",
        "\uA73D","\uA74F","\uA761","\uA769","\uA76B","\uA76D","\uA76F",
        "\uA78C","\uAB53","\uA7B5","\uA7B7"]

# Blocks are either Standard ("Western"), Complex Text Layout (CTL),
# or Chinese/Japanese/Korean (CJK also known as "Asian").
# Punctuation can be used for all types so it does not determine the type,
# but it can be considered Standard if it is the only type in a string.
TYPE_INDETERMINATE = 0
TYPE_STANDARD = 1
TYPE_COMPLEX = 2
TYPE_CJK = 3

def getFontType(c, adjacentCharType=None):
    """Get the font type of the given character.
    :param c: the character to check
    :param adjacentCharType: type of surrounding characters

    Note: Looking up all strings in a document might be slow,
    but it is O(n) running time, so hopefully it shouldn't take too long.
    """
    if c.isspace() or c.isdigit() or c in string.punctuation:
        if adjacentCharType:
            return adjacentCharType
        return TYPE_INDETERMINATE
    for startChar, endChar, fontType in FONT_TYPE_BLOCKS:
        if startChar < c < endChar:
            return fontType
    return TYPE_STANDARD

# These code points are manually derived from the Unicode database file
# Blocks.txt, and the types are a best guess.
FONT_TYPE_BLOCKS = [
    ("\u0000", "\u007F", TYPE_STANDARD), # Basic Latin
    ("\u0080", "\u00FF", TYPE_STANDARD), # Latin-1 Supplement
    ("\u0100", "\u017F", TYPE_STANDARD), # Latin Extended-A
    ("\u0180", "\u024F", TYPE_STANDARD), # Latin Extended-B
    ("\u0250", "\u02AF", TYPE_STANDARD), # IPA Extensions
    ("\u02B0", "\u02FF", TYPE_STANDARD), # Spacing Modifier Letters
    ("\u0300", "\u036F", TYPE_STANDARD), # Combining Diacritical Marks
    ("\u0370", "\u03FF", TYPE_STANDARD), # Greek and Coptic
    ("\u0400", "\u04FF", TYPE_STANDARD), # Cyrillic
    ("\u0500", "\u052F", TYPE_STANDARD), # Cyrillic Supplement
    ("\u0530", "\u058F", TYPE_STANDARD), # Armenian
    ("\u0590", "\u05FF", TYPE_COMPLEX), # Hebrew
    ("\u0600", "\u06FF", TYPE_COMPLEX), # Arabic
    ("\u0700", "\u074F", TYPE_STANDARD), # Syriac
    ("\u0750", "\u077F", TYPE_COMPLEX), # Arabic Supplement
    ("\u0780", "\u07BF", TYPE_STANDARD), # Thaana
    ("\u07C0", "\u07FF", TYPE_STANDARD), # NKo
    ("\u0800", "\u083F", TYPE_STANDARD), # Samaritan
    ("\u0840", "\u085F", TYPE_STANDARD), # Mandaic
    ("\u08A0", "\u08FF", TYPE_COMPLEX), # Arabic Extended-A
    ("\u0900", "\u097F", TYPE_COMPLEX), # Devanagari
    ("\u0980", "\u09FF", TYPE_COMPLEX), # Bengali
    ("\u0A00", "\u0A7F", TYPE_COMPLEX), # Gurmukhi
    ("\u0A80", "\u0AFF", TYPE_COMPLEX), # Gujarati
    ("\u0B00", "\u0B7F", TYPE_COMPLEX), # Oriya
    ("\u0B80", "\u0BFF", TYPE_COMPLEX), # Tamil
    ("\u0C00", "\u0C7F", TYPE_COMPLEX), # Telugu
    ("\u0C80", "\u0CFF", TYPE_COMPLEX), # Kannada
    ("\u0D00", "\u0D7F", TYPE_COMPLEX), # Malayalam
    ("\u0D80", "\u0DFF", TYPE_COMPLEX), # Sinhala
    ("\u0E00", "\u0E7F", TYPE_COMPLEX), # Thai
    ("\u0E80", "\u0EFF", TYPE_COMPLEX), # Lao
    ("\u0F00", "\u0FFF", TYPE_COMPLEX), # Tibetan
    ("\u1000", "\u109F", TYPE_COMPLEX), # Myanmar
    ("\u10A0", "\u10FF", TYPE_STANDARD), # Georgian
    ("\u1100", "\u11FF", TYPE_STANDARD), # Hangul Jamo
    ("\u1200", "\u137F", TYPE_STANDARD), # Ethiopic
    ("\u1380", "\u139F", TYPE_STANDARD), # Ethiopic Supplement
    ("\u13A0", "\u13FF", TYPE_STANDARD), # Cherokee
    ("\u1400", "\u167F", TYPE_STANDARD), # Canadian Aboriginal Syllabics
    ("\u1680", "\u169F", TYPE_STANDARD), # Ogham
    ("\u16A0", "\u16FF", TYPE_STANDARD), # Runic
    ("\u1700", "\u171F", TYPE_STANDARD), # Tagalog
    ("\u1720", "\u173F", TYPE_STANDARD), # Hanunoo
    ("\u1740", "\u175F", TYPE_STANDARD), # Buhid
    ("\u1760", "\u177F", TYPE_STANDARD), # Tagbanwa
    ("\u1780", "\u17FF", TYPE_COMPLEX), # Khmer
    ("\u1800", "\u18AF", TYPE_COMPLEX), # Mongolian
    ("\u18B0", "\u18FF", TYPE_STANDARD), # Canadian Aboriginal Syll. Ext.
    ("\u1900", "\u194F", TYPE_STANDARD), # Limbu
    ("\u1950", "\u197F", TYPE_STANDARD), # Tai Le
    ("\u1980", "\u19DF", TYPE_STANDARD), # New Tai Lue
    ("\u19E0", "\u19FF", TYPE_COMPLEX), # Khmer Symbols
    ("\u1A00", "\u1A1F", TYPE_STANDARD), # Buginese
    ("\u1A20", "\u1AAF", TYPE_STANDARD), # Tai Tham
    ("\u1AB0", "\u1AFF", TYPE_STANDARD), # Combining Diacritic Marks Ext.
    ("\u1B00", "\u1B7F", TYPE_STANDARD), # Balinese
    ("\u1B80", "\u1BBF", TYPE_STANDARD), # Sundanese
    ("\u1BC0", "\u1BFF", TYPE_STANDARD), # Batak
    ("\u1C00", "\u1C4F", TYPE_STANDARD), # Lepcha
    ("\u1C50", "\u1C7F", TYPE_STANDARD), # Ol Chiki
    ("\u1CC0", "\u1CCF", TYPE_STANDARD), # Sundanese Supplement
    ("\u1CD0", "\u1CFF", TYPE_STANDARD), # Vedic Extensions
    ("\u1D00", "\u1D7F", TYPE_STANDARD), # Phonetic Extensions
    ("\u1D80", "\u1DBF", TYPE_STANDARD), # Phonetic Extensions Supplement
    ("\u1DC0", "\u1DFF", TYPE_STANDARD), # Combining Diacritic Marks Supp
    ("\u1E00", "\u1EFF", TYPE_STANDARD), # Latin Extended Additional
    ("\u1F00", "\u1FFF", TYPE_STANDARD), # Greek Extended
    ("\u2000", "\u206F", TYPE_STANDARD), # General Punctuation
    ("\u2070", "\u209F", TYPE_STANDARD), # Superscripts and Subscripts
    ("\u20A0", "\u20CF", TYPE_STANDARD), # Currency Symbols
    ("\u20D0", "\u20FF", TYPE_STANDARD), # Combining Marks for Symbols
    ("\u2100", "\u214F", TYPE_STANDARD), # Letterlike Symbols
    ("\u2150", "\u218F", TYPE_STANDARD), # Number Forms
    ("\u2190", "\u21FF", TYPE_STANDARD), # Arrows
    ("\u2200", "\u22FF", TYPE_STANDARD), # Mathematical Operators
    ("\u2300", "\u23FF", TYPE_STANDARD), # Miscellaneous Technical
    ("\u2400", "\u243F", TYPE_STANDARD), # Control Pictures
    ("\u2440", "\u245F", TYPE_STANDARD), # Optical Character Recognition
    ("\u2460", "\u24FF", TYPE_STANDARD), # Enclosed Alphanumerics
    ("\u2500", "\u257F", TYPE_STANDARD), # Box Drawing
    ("\u2580", "\u259F", TYPE_STANDARD), # Block Elements
    ("\u25A0", "\u25FF", TYPE_STANDARD), # Geometric Shapes
    ("\u2600", "\u26FF", TYPE_STANDARD), # Miscellaneous Symbols
    ("\u2700", "\u27BF", TYPE_STANDARD), # Dingbats
    ("\u27C0", "\u27EF", TYPE_STANDARD), # Miscellaneous Math Symbols-A
    ("\u27F0", "\u27FF", TYPE_STANDARD), # Supplemental Arrows-A
    ("\u2800", "\u28FF", TYPE_STANDARD), # Braille Patterns
    ("\u2900", "\u297F", TYPE_STANDARD), # Supplemental Arrows-B
    ("\u2980", "\u29FF", TYPE_STANDARD), # Miscellaneous Math Symbols-B
    ("\u2A00", "\u2AFF", TYPE_STANDARD), # Supplemental Math Operators
    ("\u2B00", "\u2BFF", TYPE_STANDARD), # Misc Symbols and Arrows
    ("\u2C00", "\u2C5F", TYPE_STANDARD), # Glagolitic
    ("\u2C60", "\u2C7F", TYPE_STANDARD), # Latin Extended-C
    ("\u2C80", "\u2CFF", TYPE_STANDARD), # Coptic
    ("\u2D00", "\u2D2F", TYPE_STANDARD), # Georgian Supplement
    ("\u2D30", "\u2D7F", TYPE_STANDARD), # Tifinagh
    ("\u2D80", "\u2DDF", TYPE_STANDARD), # Ethiopic Extended
    ("\u2DE0", "\u2DFF", TYPE_STANDARD), # Cyrillic Extended-A
    ("\u2E00", "\u2E7F", TYPE_STANDARD), # Supplemental Punctuation
    ("\u2E80", "\u2EFF", TYPE_CJK), # CJK Radicals Supplement
    ("\u2F00", "\u2FDF", TYPE_STANDARD), # Kangxi Radicals
    ("\u2FF0", "\u2FFF", TYPE_STANDARD), # Ideographic Description Chars
    ("\u3000", "\u303F", TYPE_CJK), # CJK Symbols and Punctuation
    ("\u3040", "\u309F", TYPE_CJK), # Hiragana
    ("\u30A0", "\u30FF", TYPE_CJK), # Katakana
    ("\u3100", "\u312F", TYPE_STANDARD), # Bopomofo
    ("\u3130", "\u318F", TYPE_CJK), # Hangul Compatibility Jamo
    ("\u3190", "\u319F", TYPE_STANDARD), # Kanbun
    ("\u31A0", "\u31BF", TYPE_STANDARD), # Bopomofo Extended
    ("\u31C0", "\u31EF", TYPE_CJK), # CJK Strokes
    ("\u31F0", "\u31FF", TYPE_STANDARD), # Katakana Phonetic Extensions
    ("\u3200", "\u32FF", TYPE_CJK), # Enclosed CJK Letters & Months
    ("\u3300", "\u33FF", TYPE_CJK), # CJK Compatibility
    ("\u3400", "\u4DBF", TYPE_CJK), # CJK Unified Ideographs Ext A
    ("\u4DC0", "\u4DFF", TYPE_CJK), # Yijing Hexagram Symbols
    ("\u4E00", "\u9FFF", TYPE_CJK), # CJK Unified Ideographs
    ("\uA000", "\uA48F", TYPE_CJK), # Yi Syllables
    ("\uA490", "\uA4CF", TYPE_CJK), # Yi Radicals
    ("\uA4D0", "\uA4FF", TYPE_STANDARD), # Lisu
    ("\uA500", "\uA63F", TYPE_STANDARD), # Vai
    ("\uA640", "\uA69F", TYPE_STANDARD), # Cyrillic Extended-B
    ("\uA6A0", "\uA6FF", TYPE_STANDARD), # Bamum
    ("\uA700", "\uA71F", TYPE_STANDARD), # Modifier Tone Letters
    ("\uA720", "\uA7FF", TYPE_STANDARD), # Latin Extended-D
    ("\uA800", "\uA82F", TYPE_STANDARD), # Syloti Nagri
    ("\uA830", "\uA83F", TYPE_COMPLEX), # Common Indic Number Forms
    ("\uA840", "\uA87F", TYPE_STANDARD), # Phags-pa
    ("\uA880", "\uA8DF", TYPE_STANDARD), # Saurashtra
    ("\uA8E0", "\uA8FF", TYPE_COMPLEX), # Devanagari Extended
    ("\uA900", "\uA92F", TYPE_STANDARD), # Kayah Li
    ("\uA930", "\uA95F", TYPE_STANDARD), # Rejang
    ("\uA960", "\uA97F", TYPE_CJK), # Hangul Jamo Extended-A
    ("\uA980", "\uA9DF", TYPE_STANDARD), # Javanese
    ("\uA9E0", "\uA9FF", TYPE_COMPLEX), # Myanmar Extended-B
    ("\uAA00", "\uAA5F", TYPE_STANDARD), # Cham
    ("\uAA60", "\uAA7F", TYPE_COMPLEX), # Myanmar Extended-A
    ("\uAA80", "\uAADF", TYPE_STANDARD), # Tai Viet
    ("\uAAE0", "\uAAFF", TYPE_STANDARD), # Meetei Mayek Extensions
    ("\uAB00", "\uAB2F", TYPE_STANDARD), # Ethiopic Extended-A
    ("\uAB30", "\uAB6F", TYPE_STANDARD), # Latin Extended-E
    ("\uAB70", "\uABBF", TYPE_STANDARD), # Cherokee Supplement
    ("\uABC0", "\uABFF", TYPE_STANDARD), # Meetei Mayek
    ("\uAC00", "\uD7AF", TYPE_CJK), # Hangul Syllables
    ("\uD7B0", "\uD7FF", TYPE_CJK), # Hangul Jamo Extended-B
    ("\uD800", "\uDB7F", TYPE_STANDARD), # High Surrogates
    ("\uDB80", "\uDBFF", TYPE_STANDARD), # High Private Use Surrogates
    ("\uDC00", "\uDFFF", TYPE_STANDARD), # Low Surrogates
    ("\uE000", "\uF8FF", TYPE_STANDARD), # Private Use Area
    ("\uF900", "\uFAFF", TYPE_CJK), # CJK Compatibility Ideographs
    ("\uFB00", "\uFB4F", TYPE_STANDARD), # Alphabetic Presentation Forms
    ("\uFB50", "\uFDFF", TYPE_COMPLEX), # Arabic Presentation Forms-A
    ("\uFE00", "\uFE0F", TYPE_STANDARD), # Variation Selectors
    ("\uFE10", "\uFE1F", TYPE_STANDARD), # Vertical Forms
    ("\uFE20", "\uFE2F", TYPE_STANDARD), # Combining Half Marks
    ("\uFE30", "\uFE4F", TYPE_CJK), # CJK Compatibility Forms
    ("\uFE50", "\uFE6F", TYPE_STANDARD), # Small Form Variants
    ("\uFE70", "\uFEFF", TYPE_COMPLEX), # Arabic Presentation Forms-B
    ("\uFF00", "\uFFEF", TYPE_STANDARD), # Halfwidth and Fullwidth Forms
    ("\uFFF0", "\uFFFF", TYPE_STANDARD), # Specials
    ]
