#include <com/sun/star/uno/XInterface.idl>

module name { module JimK { module LinguisticTools { module CalcFunctions {

    interface XCalcFunctions
    {
      string reverse( [in] string s );
    };

}; }; }; };
